swagger:
  enabled: false
  info:
    title: stratio- Microservice API
    description: stratio- Microservice API Description
    version: v1


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    org.apache: WARN
    org.eclipse: WARN
    com.netflix: INFO


spring:
  datasource:
        url: jdbc:postgresql://poolpostgrestls.anjana.local:10234/postgres?user=fjurado&prepareThreshold=0&reWriteBatchedInserts=true&ssl=true&sslmode=verify-ca&sslcert=/home/apaniagua/Documentos/aurgi/certs/Certificado Postgres (conexión desde exterior)/fjurado.crt&sslrootcert=/home/apaniagua/Documentos/aurgi/certs/Certificado Postgres (conexión desde exterior)/root-ca.crt&sslkey=/home/apaniagua/Documentos/aurgi/certs/Certificado Postgres (conexión desde exterior)/fjurado.pk8&loginTimeout=60
        username: fjurado
        password:

#url: jdbc:postgresql://localhost:5432/postgres?useSSL=false&currentSchema=motortown
#username: postgres


sftphost: 10.20.1.112
sftpuser: motortown_watcher
productsfile: anjana/in/motortown_productos_servicios.csv
stockfile: anjana/in/motortown_stock_por_centro.csv
pricatfile: anjana/in/pricat_ctop.csv
sftpkey: /home/apaniagua/.ssh/id_rsa
sftpoutfolder: /anjana/motortown_pro/ingesta_productos_stock/procesado/
schedulerRate: 600000
sftpoutputformat: zip
sftpsplitfiles: false
sftpdifffiles: false

server:
  port: 8888